[package]
name = "samotop"
version = "0.7.0"
authors = ["jocutajar <tellnoone@robajz.info>"]
build = "src/peg.rs"
exclude = [
    "downloads/*"
]
description = "SMTP server and library built on tokio-rs"
documentation = "https://docs.rs/samotop/"
homepage = "https://gitlab.com/BrightOpen/BackYard/Samotop/"
repository = "https://gitlab.com/BrightOpen/BackYard/Samotop/"
readme = "README.md"
keywords = ["smtp", "tokio", "server", "parser", "PEG"]

# see crates.io/category_slugs
categories = ["email", "asynchronous", "network-programming", "parser-implementations"]
license = "MIT"

[badges]
gitlab = { repository = "BrightOpen/BackYard/Samotop", branch = "develop" }

[dependencies]
log = "0.4"
env_logger = "0.5"
structopt = "0.2"
peg = "0.5"
tokio = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1"
futures = "0.1"
bytes = "0.4"
regex = "1.0"
hostname = "0.1"
uuid = { version = "0.6", features = ["v4"] }

[build-dependencies]
peg = { version = "0.5" }