[package]
name = "samotop"
version = "0.3.0"
authors = ["jocutajar <tellnoone@robajz.info>"]
build = "src/peg.rs"

[dependencies]
log = "0.4"
env_logger = "0.5"
structopt = "0.2"
peg = "0.5"
tokio = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1"
futures = "0.1"
bytes = "0.4"
regex = "1.0"
hostname = "0.1"

[build-dependencies]
peg = { version = "0.5" }