[workspace]
members = [
    "samotop-delivery",
    "samotop-model",
    "samotop-core",
    "samotop-parser",
    #"samotop-parser-nom",
    "samotop-with-spf",
    "samotop",
    "samotop-server",
]
