[package]
name = "samotop"
version = "0.7.5"
authors = ["jocutajar <tellnoone@robajz.info>"]
exclude = [
    "downloads/*"
]
description = "SMTP server and library built on tokio-rs"
documentation = "https://docs.rs/samotop/"
homepage = "https://gitlab.com/BrightOpen/BackYard/Samotop/"
repository = "https://gitlab.com/BrightOpen/BackYard/Samotop/"
readme = "README.md"
keywords = ["smtp", "tokio", "server", "parser", "PEG"]
#edition = "2018"

# see crates.io/category_slugs
categories = ["email", "asynchronous", "network-programming", "parser-implementations"]
license = "MIT"

[badges]
gitlab = { repository = "BrightOpen/BackYard/Samotop", branch = "develop" }

[features]
tls = ["native-tls"]

[dependencies]
log = "0.4"
env_logger = "0.7"
structopt = "0.3"
peg = "0.6"
tokio = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1"
futures = "0.1"
bytes = "0.4"
regex = "1.3"
hostname = "0.3"
uuid = { version = "0.8", features = ["v4"] }
native-tls = { version = "0.2", optional = true }
secstr = "0.4"
