[package]
name = "samotop-core"
version = "0.10.0-preview.1"
authors = ["jocutajar <tellnoone@robajz.info>"]
description = "Base crate for Samotop extensions"
documentation = "https://docs.rs/samotop/"
homepage = "https://gitlab.com/BrightOpen/BackYard/Samotop/"
repository = "https://gitlab.com/BrightOpen/BackYard/Samotop/"
keywords = ["smtp", "async", "server"]
edition = "2018"

# see crates.io/category_slugs 
categories = [
    "email",
    "asynchronous",
    "network-programming",
    "parser-implementations",
]
license = "MIT"

[badges]
gitlab = { repository = "BrightOpen/BackYard/Samotop", branch = "develop" }
maintenance = { status = "actively-developed" }

[dependencies.samotop-model]
version = "0.10.0-preview.1"
path = "../samotop-model"

[dependencies]
log = "0.4"
futures = { version = "0.3", default-features = false, features = ["std"] }
pin-project = "0.4"
uuid = { version = "0.8", features = ["v4"] }
bytes = "0.5"
memchr = "2.3"
