[package]
name = "samotop-core"
version = "0.12.0"
authors = ["jocutajar <tellnoone@robajz.info>"]
license = "MIT OR Apache-2.0"
description = "Core samotop functionality"
documentation = "https://docs.rs/samotop/"
homepage = "https://gitlab.com/BrightOpen/BackYard/Samotop/-/tree/develop/samotop-core"
repository = "https://gitlab.com/BrightOpen/BackYard/Samotop/"
keywords = ["smtp", "async", "server"]
edition = "2018"

# see crates.io/category_slugs 
categories = [
    "email",
    "asynchronous",
    "network-programming",
    "parser-implementations",
]

[badges]
gitlab = { repository = "BrightOpen/BackYard/Samotop", branch = "develop" }
maintenance = { status = "actively-developed" }

[dependencies.samotop-model]
version = "0.12.0"
path = "../samotop-model"

[dependencies]
log = "0.4"
futures = { version = "0.3", default-features = false, features = ["std"] }
async-std = {version = "1.7", default-features = false, features = []}
pin-project = "1.0"
bytes = "0.6"
memchr = "2.3"