[package]
name = "samotop"
version = "0.9.1-snapshot"
authors = ["jocutajar <tellnoone@robajz.info>"]
description = "SMTP server and library built on async-std"
documentation = "https://docs.rs/samotop/"
homepage = "https://gitlab.com/BrightOpen/BackYard/Samotop/"
repository = "https://gitlab.com/BrightOpen/BackYard/Samotop/"
readme = "README.md"
keywords = ["smtp", "async", "server", "parser", "PEG"]
edition = "2018"

# see crates.io/category_slugs
categories = [
    "email",
    "asynchronous",
    "network-programming",
    "parser-implementations",
]
license = "MIT"

[badges]
gitlab = { repository = "BrightOpen/BackYard/Samotop", branch = "develop" }

[features]
default = ["rust-tls", "spf"]
spf = ["viaspf", "trust-dns-resolver"]
rust-tls = ["async-tls"]
#native-tls = ["async-native-tls"]

[dependencies]
log = "0.4"
peg = "0.6"
bytes = "0.5"
uuid = { version = "0.8", features = ["v4"] }
pin-project = "0.4"
memchr = "2.3"
chrono = "0.4"
futures = "0.3"
async-std = "1.6"
async-tls = { version = "0.9", optional = true }
#rustls = { version = "0.18", optional = true }
async-native-tls = { version = "0.3", optional = true }
viaspf = { version = "0", optional = true }
trust-dns-resolver = { version = "0.19", optional = true, default-features = false, features = ["tokio-runtime"] }

[dev-dependencies]
futures-await-test = "0.3"
env_logger = "0.7"
